version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    networks:
      - microservice-network
    volumes:
      - sqlserverdata:/var/opt/mssql

  loja-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loja-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=LojaDb;User Id=sa;Password=Your_password123;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  sqlserverdata:
