services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LojaDb123
    ports:
      - "1433:1433"
    networks:
      - microservice-network
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/1433"]
      interval: 20s 
      timeout: 30s
      retries: 5
      start_period: 30s


  loja-api:
    container_name: loja-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    networks:
      - microservice-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MASTER;User Id=sa;Password=LojaDb123;TrustServerCertificate=True
    depends_on: ["sqlserver"]
    restart: unless-stopped


networks:
  microservice-network:
    driver: bridge

volumes:
  sqlserverdata:
